name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [Nice to have, Important, Critical]
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have searched for existing issues and this is not a duplicate.
          required: true
